wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.5
    session_history: code\_session_history.ipynb
    start_time: 1657319171
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      4: 3.10.5
      5: 0.12.20
      8:
      - 1
      - 3
      - 5
