wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.5
    start_time: 1657323076
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      4: 3.10.5
      5: 0.12.20
      8:
      - 3
      - 5
